version: '3.8'

services:
  fastapi.example.storybooks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 5010:80
      - 7010:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  fastapi.postgre:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: 5ecretPostgrePassword # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: SB # The PostgreSQL default database (automatically created at first launch)